spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: 1234
    driverClassName: org.h2.Driver

  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2dialect
  h2:
    console.enable: true